FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src

# Копируем csproj и восстанавливаем зависимости
COPY Mafia.csproj .
RUN dotnet restore

EXPOSE 8080

# Команда будет переопределена в docker-compose
CMD ["dotnet", "watch", "run"]

